---
abstract: 'Tools to help make git workflows easier'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: git-workflow-tools
provides:
  Git::Workflow:
    file: lib/Git/Workflow.pm
    version: 0.5
  Git::Workflow::Pom:
    file: lib/Git/Workflow/Pom.pm
    version: 0.5
  Git::Workflow::Repository:
    file: lib/Git/Workflow/Repository.pm
    version: 0.5
recommends:
  JSON::XS: 2.34
requires:
  Error: 0
  Git: 0
  Path::Class: 0
  Time::Piece: 0
  XML::Tiny: 0
  autodie: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=git-workflow-tools
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/git-workflow-tools.git
version: 0.5
